config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'home#index'
  match ":controller(/:action(/:id))", via: [:get, :post]

end

app/models/c_category.rb
class CCategory < ActiveRecord::Base
    has_many :clubs
end

app/models/club.rb
class Club < ActiveRecord::Base
    belongs_to :c_category
    has_many :festivals
    has_many :recruits
    
    has_many :users_clubs
    has_many :users, through: :users_clubs
end

app/models/festival.rb
class Festival < ActiveRecord::Base
    belongs_to :club
end

app/models/recruit.rb
class Recruit < ActiveRecord::Base
    belongs_to :club
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :users_clubs
  has_many :clubs, through: :users_clubs
  
end

app/models/users_club.rb
class UsersClub < ActiveRecord::Base
    belongs_to :user
    belongs_to :club
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
  def require_login
  	unless user_signed_in?
  		redirect_to "/users/sign_in"
  	end
  end  

    before_filter :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }
            devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
        end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :require_login

  def index
  end
  
  def club_my
    
    @c = UsersClub.where(user_id: current_user.id)
  end
  
  def club_detail
    @detail = Club.find(params[:id])
  end
  
  
  def club_make_view
  end
  
  def club_make
    c = Club.new(name:params[:club_name], about:params[:club_about], profile_pic:params[:club_profile], cover_pic:params[:club_cover])
    c.save
    
    unless UsersClub.where(user_id:current_user.id).where(club_id: c.id).first
      k = UsersClub.new
      k.user_id = current_user.id
      k.club_id = c.id
      k.save
    end
    
    redirect_to "/home/club_show"
  end
  
  def club_join
    
    unless UsersClub.where(user_id:current_user.id).where(club_id: params[:id]).first
      k = UsersClub.new
      k.user_id = current_user.id
      k.club_id = params[:id]
      k.save
    end
    
    
    redirect_to "/home/club_detail/#{params[:id]}"    
  end
  
  def club_destory
    d = Club.find(params[:id])
    d.destroy
    
    redirect_to :back
  end
  
  def club_show
    @club = Club.all
  end
  
  def festival_all
    @k = params[:id]
    @f = Club.find(params[:id])
    
  end
  
  def festival_make
    f = Festival.new(club_id:params[:club_id], name:params[:festival_name], about:params[:festival_about], date:params[:festival_date], festival_pic:params[:festival_pic])
    f.save
    
    redirect_to :back
  end
  
  def recruit_all
    @k = params[:id]
    @f = Club.find(params[:id])
  end   
  
  def recruit_make
    f = Recruit.new(club_id:params[:club_id], name:params[:recruit_name], about:params[:recruit_about], date:params[:recruit_date], recruit_pic:params[:recruit_pic])
    f.save
    
    redirect_to :back
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/club_detail.erb
<div class="container">
    <a href="/home/index">[돌아가기]</a>
    <% k = @detail %>
    <div class="well">
        <p>동아리명: <%= k.name %></p>
        <p>설명 : <%= k.about %></p>
        <p>프로필사진 : <%= k.profile_pic %></p>
        <p>커버사진 : <%= k.cover_pic %></p>
        <a href="/home/festival_all/<%= k.id %>">행사등록</a><br>
        <a href="/home/recruit_all/<%= k.id %>">부원모집등록</a><br>
        <hr>
        <a href="/home/club_join/<%=k.id %>">[가입하기]</a>
        <a href="/home/club_destory/<%= k.id %>">[삭제]</a>
        <hr>
        
        <p>
            
            회원들 :
            <% k.users.each do |z| %>
            <%= z.name %>
            <% end %>
        </p>
    </div>
</div>

app/views/home/club_make_view.erb
<div class="container">
    <form action="/home/club_make" method="POST" enctype="multipart/form-data">
      <div class="form-group">
        <label for="exampleInputEmail1">동아리명</label>
        <input name="club_name" type="text" class="form-control" id="exampleInputEmail1" placeholder="동아리명">
      </div>
      
      <label for="exampleInputEmail1">동아리설명</label>      
      <textarea name="club_about" class="form-control" rows="5" id="comment"></textarea>

      <div class="form-group">      
          <label for="exampleInputEmail1">카테고리</label>
            <select name="club_category">
              <option value="예술">예술</option>
              <option value="학술">학술</option>
              <option value="봉사">봉사</option>
              <option value="기타">기타</option>
            </select>      
      </div>
      
      <div class="form-group">
        <label for="exampleInputFile">동아리 프로필사진</label>
        <input type="file" id="club_profile">
      </div> 
      
      <div class="form-group">
        <label for="exampleInputFile">동아리 커버 사진</label>
        <input type="file" id="club_cover">
      </div>
      
      <button type="submit" class="btn btn-default">Submit</button>
</form>    
</div>

app/views/home/club_my.erb
<div class="container">
    <a href="/home/index">[돌아가기]</a>
    <h1>내가 가입한 동아리 리스트</h1>
    <% @c.each do |m| %>
        <% club = Club.where(id:m.club_id).first %>
        <p><a href="/home/club_detail/<%= club.id %>"><%= club.name %></a></p>
    <% end %>
</div>

app/views/home/club_show.erb
<div class="container">
    <div class="row">
        
        <a href="/home/index">[돌아가기]</a><br>
        <h1>동아리 리스트</h1>
        
        <% @club.each do |x| %>
        
            <p><a href="/home/club_detail/<%= x.id %>"><%= x.name %></a></p>

        <% end %>
    </div>
</div>

app/views/home/festival_all.erb
<div class="container">
    <a href="/home/club_show">[동아리 리스트로 돌아가기]</a>
    <hr>
    <h1>행사 리스트/만들기</h1>
    <hr>
    
    <%= form_tag({action: :"/home/festival_make"}, multipart: true) do %>
      <%= file_field_tag 'picture' %>
    <% end %>
    
    <form action="/home/festival_make" method="POST" enctype="multipart/form-data">
      <div class="form-group">
        <label for="exampleInputEmail1">행사명</label>
        <input name="festival_name" type="text" class="form-control" id="exampleInputEmail1" placeholder="동아리명">
      </div>

      <div class="form-group">
        <label for="exampleInputEmail1">행사시간</label>
        <input name="festival_date" type="text" class="form-control" id="exampleInputEmail1" placeholder="동아리명">
      </div>
      
      <label for="exampleInputEmail1">행사설명</label>      
      <textarea name="festival_about" class="form-control" rows="5" id="comment"></textarea>

      
      <div class="form-group">
        <label for="exampleInputFile">행사사진</label>
        <input name="festival_pic" type="file" id="club_profile">
      </div> 
      
        <input name="club_id" type="hidden" value="<%= @k %>">

      <button type="submit" class="btn btn-default">Submit</button>
    </form>    
    <hr>
    
    
        <% @f.festivals.each do |p| %>
            <div class="well">
                행사명 : <%= p.name %><br>
                행사시간 : <%= p.date %><br>
                행사설명 : <%= p.about %><br>
                행사사진 : <%= p.festival_pic %><br>
            </div>
        <% end %>

    
</div>

app/views/home/index.erb
<a href="/users/sign_out">[로그아웃]</a>
<p>현재 유저: <%= current_user.name %></p>
<h1><a href="/home/club_show">전체 동아리 리스트 보기</a></h1>
<h1><a href="/home/club_make_view">동아리 만들기</a></h1>
<a href="/home/club_my">내가 가입한 동아리 리스트 보기</a>

app/views/home/recruit_all.erb
<div class="container">
    <a href="/home/club_show">[동아리 리스트로 돌아가기]</a>
    <hr>
    <h1>부원모집 리스트/만들기</h1>
    <hr>
    <form action="/home/recruit_make" method="POST" enctype="multipart/form-data">
      <div class="form-group">
        <label for="exampleInputEmail1">모집제목</label>
        <input name="recruit_name" type="text" class="form-control" id="exampleInputEmail1" placeholder="동아리명">
      </div>

      <div class="form-group">
        <label for="exampleInputEmail1">모집기간</label>
        <input name="recruit_date" type="text" class="form-control" id="exampleInputEmail1" placeholder="동아리명">
      </div>
      
      <label for="exampleInputEmail1">모집설명</label>      
      <textarea name="recruit_about" class="form-control" rows="5" id="comment"></textarea>

      
      <div class="form-group">
        <label for="exampleInputFile">모집사진</label>
        <input name="recruit_pic" type="file" id="club_profile">
      </div> 
      
        <input name="club_id" type="hidden" value="<%= @k %>">

      <button type="submit" class="btn btn-default">Submit</button>
    </form>    
    <hr>
    
        <% @f.recruits.each do |p| %>
            <div class="well">
                모집명 : <%= p.name %><br>
                모집기간 : <%= p.date %><br>
                모집설명 : <%= p.about %><br>
                모집사진 : <%= p.recruit_pic %><br>
            </div>
        <% end %>
    
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SogangBook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


<!--일단 bootstrap cdn 추가함 .정현-->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  
  
  
  
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>